obj-$(CONFIG_SND_SOC_AW882XX) += aw882xx/
obj-$(CONFIG_SND_SOC_CS35LXX) += cs35lxx/
obj-$(CONFIG_SND_SOC_TFA98XX) += tfa98xx/
subdir-ccflags-y += -Wno-unused-but-set-variable -Wno-strict-prototypes -Wno-incompatible-pointer-types-discards-qualifiers
