#
# Makefile for network qos sched
#

obj-$(CONFIG_HW_NETQOS_SCHED) += network_qos.o
subdir-ccflags-y += -Wno-unused-but-set-variable -Wno-strict-prototypes -Wno-incompatible-pointer-types-discards-qualifiers
